# Site settings
title: 700apps
email: sammycheung@me.com
description: talk apps
baseurl: 
url: http://700apps.xyz
twitter_username: sammycheung
github_username:  iSammyC



# Build settings
markdown: kramdown

