# Site settings
title: 700apps
email: sammy@700apps.xyz
description: all about apps
baseurl: 
url: http://700apps.xyz
twitter_username: sammycheung
github_username:  iSammyC



# Build settings
markdown: kramdown

